(source gnu)
(source melpa)

;;; basic
(depends-on "exec-path-from-shell")
(depends-on "init-loader")

;; edit
(depends-on "expand-region")
(depends-on "multiple-cursors")
(depends-on "undo-tree")

;; feel
(depends-on "ace-jump-mode")
(depends-on "goto-chg")
(depends-on "jump-char")
(depends-on "point-undo")
(depends-on "smartrep")

;; look
(depends-on "anzu")
(depends-on "highlight-symbol")
(depends-on "rainbow-delimiters")
(depends-on "rainbow-mode")

;;; utility
;; helm
(depends-on "helm")
(depends-on "helm-ag")
(depends-on "helm-descbinds")
(depends-on "helm-ghq")
(depends-on "helm-gtags")
(depends-on "helm-ls-git")
(depends-on "helm-projectile")

(depends-on "projectile")

;; auto-complete
(depends-on "auto-complete")
(depends-on "fuzzy")
(depends-on "popup")

;; yasnippet
(depends-on "yasnippet")

;; flycheck
(depends-on "flycheck")
(depends-on "flycheck-tip")

;; VCS
(depends-on "gist")
(depends-on "git-gutter")
(depends-on "magit")

;; window, buffer management
(depends-on "popwin")
(depends-on "tabbar")

(depends-on "direx")
(depends-on "guide-key")
(depends-on "open-junk-file")
(depends-on "quickrun")
(depends-on "recentf-ext")
(depends-on "zeal-at-point")

;;; languages
;; C/C++
(depends-on "auto-complete-clang" :git "https://github.com/yuttie/auto-complete-clang" :branch "fix-missing-standard-include-files")
;; (depends-on "auto-complete-clang-async")
(depends-on "c-eldoc")

;; Go
(depends-on "go-autocomplete")
(depends-on "go-eldoc")
(depends-on "go-mode")
(depends-on "helm-go-package")

;; Python
(depends-on "jedi")

;; Ruby
(depends-on "robe")
(depends-on "rspec-mode")
(depends-on "ruby-end")

;; JavaScript
(depends-on "coffee-mode")
(depends-on "js2-mode")

;; scripting
(depends-on "dockerfile-mode")
(depends-on "terraform-mode")

;; web
(depends-on "emmet-mode")
(depends-on "haml-mode")
(depends-on "json-mode")
(depends-on "scss-mode")
(depends-on "web-mode")
(depends-on "yaml-mode")

;; editing
(depends-on "gitignore-mode")
(depends-on "markdown-mode")
(depends-on "toml-mode")

;;; theme
(depends-on "monokai-theme")
(depends-on "powerline")
