#!/usr/bin/env zsh
# Insert the selected git commit hash into the command line

if ! git rev-parse --is-inside-work-tree &> /dev/null; then
  return
fi

local hash=$(git log --oneline | fzf-tmux --prompt 'hash> ' | cut -d' ' -f1)
[[ -z $hash ]] && return

LBUFFER=${LBUFFER}${hash}
zle reset-prompt
typeset -f zle-line-init > /dev/null && zle zle-line-init
