#!/usr/bin/env zsh
# Run `ls && git status`

echo
ls

if git rev-parse --is-inside-work-tree &> /dev/null; then
  echo -e '\n\e[0;33m--- git status ---\e[0m'
  git status -sb
fi

echo '\n' # avoid being not displayed when PROMPT contains newline
zle reset-prompt
